---
sudo: required

 
script:
 
  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook test/ntp.yml test/httpd.yml --syntax-check'

  # Test role.
   - ansible-playbook -i test/inventory test/httpd.yml --syntax-check

  # Test role idempotence.
 # Run the role/playbook again, checking to make sure it's idempotent.
   - >
     ansible-playbook -i test/inventory test/httpd.yml --connection=local --sudo
     | grep -q 'changed=0.*failed=0'
     && (echo 'Idempotence test: pass' && exit 0)
     || (echo 'Idempotence test: fail' && exit 1)
# Request a page via the web server, to make sure it's running and responds.
   - "curl http://localhost/"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
