---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
 
  # Ansible syntax check.
   - ansible-playbook -i test/inventory test/httpd.yml --syntax-check

  # Test role.
   - "ansible-playbook -i test/inventory test/httpd.yml --connection=local --sudo"

  # Test role idempotence.
 # Run the role/playbook again, checking to make sure it's idempotent.
   - >
     ansible-playbook -i test/inventory test/httpd.yml --connection=local --sudo
     | grep -q 'changed=0.*failed=0'
     && (echo 'Idempotence test: pass' && exit 0)
     || (echo 'Idempotence test: fail' && exit 1)
  # Request a page via the web server, to make sure it's running and responds.
   - "curl http://localhost/"
